#!/usr/bin/env node
// Bundles the ES modules into a classic script for chrome.scripting injection.
//
// Dynamic import() inside an injected script is evaluated against the *page's*
// CSP, so strict sites (Wikipedia, GitHub, most news) block it. A plain
// concatenated IIFE has no such problem.
//
// Run after editing anything in src/:  node build.js

const fs = require('fs');
const path = require('path');

// This script lives in .tools/, a sibling of ClearCopy/ — the extension it
// builds for. Everything it reads and writes is relative to that sibling.
const CLEAR_COPY = path.join(__dirname, '..', 'ClearCopy');
const SRC = path.join(CLEAR_COPY, 'src');
const OUT = path.join(CLEAR_COPY, 'src', 'extractor.bundle.js');

// Order matters: dependencies first.
const MODULES = ['debug.js', 'extract.js', 'blocks.js'];

const stripModuleSyntax = (code) => code
  .replace(/^\s*import\s+[^;]*?;\s*$/gm, '')
  .replace(/^\s*export\s+\{[^}]*\};\s*$/gm, '')
  .replace(/^export\s+(async\s+function|function|class|const|let|var)/gm, '$1');

const parts = MODULES.map((file) => {
  const code = fs.readFileSync(path.join(SRC, file), 'utf8');
  return `/* ---- ${file} ---- */\n${stripModuleSyntax(code)}`;
});

// Bumped whenever the exposed API changes, so a frame still holding an older
// bundle is replaced rather than skipped by the re-injection guard.
const API_VERSION = 30;

const bundle = `// GENERATED by build.js — do not edit. Source of truth is src/*.js
(() => {
  // Re-injection is normal (every capture injects again). Skip only when the
  // frame already has *this* version — an older one must be overwritten or its
  // missing entry points fail silently.
  if (window.__clearCopyApiVersion === ${API_VERSION}) return;
  window.__clearCopyApiVersion = ${API_VERSION};

${parts.join('\n\n')}

  window.__clearCopyExtract = (options) => extractDocument(options || {});
  window.__clearCopySelection = (options) => extractSelection(options || {});
  window.__clearCopyHasSelection = () => {
    const s = window.getSelection();
    return !!(s && !s.isCollapsed && (s.toString() || '').trim());
  };
  window.__clearCopyToMarkdown = (content) =>
    toMarkdown(htmlToBlocks(content.html), content.metadata);
  window.__clearCopyDiscoverLessonLinks = () => discoverCourseLessonLinks();
  // Whole-course walk over an ARIA lesson tree. Returns the per-lesson
  // results; the caller merges them, since collection.js is not bundled here
  // (it runs in the preview, under the extension's own CSP).
  // Walking is driven one lesson per call: forty pages of extracted HTML is
  // far more than executeScript can return in a single structured clone.
  window.__clearCopyLessonTree = () => lessonTreeSummary();
  window.__clearCopyOpenLesson = (index, options) => openLessonByIndex(index, options || {});
  window.__clearCopyFindLessonTree = () => lessonTreeSummary().titles;
})();
`;

fs.writeFileSync(OUT, bundle);
console.log(`wrote ${path.relative(path.join(__dirname, '..'), OUT)} (${(bundle.length / 1024).toFixed(1)} KB)`);
